// <auto-generated />
using System;
using KwikOff.Web.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KwikOff.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260101000824_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KwikOff.Web.Domain.Entities.ComparisonResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ComparedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("compared_at");

                    b.Property<Guid>("ComparisonBatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("comparison_batch_id");

                    b.Property<string>("ComparisonDetails")
                        .HasColumnType("jsonb")
                        .HasColumnName("comparison_details");

                    b.Property<double>("ConfidenceScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("double precision")
                        .HasColumnName("confidence_score");

                    b.Property<bool>("HasAllergenDiscrepancy")
                        .HasColumnType("boolean")
                        .HasColumnName("has_allergen_discrepancy");

                    b.Property<bool>("HasBrandDiscrepancy")
                        .HasColumnType("boolean")
                        .HasColumnName("has_brand_discrepancy");

                    b.Property<bool>("HasCategoryDiscrepancy")
                        .HasColumnType("boolean")
                        .HasColumnName("has_category_discrepancy");

                    b.Property<bool>("HasNameDiscrepancy")
                        .HasColumnType("boolean")
                        .HasColumnName("has_name_discrepancy");

                    b.Property<bool>("HasNutritionDiscrepancy")
                        .HasColumnType("boolean")
                        .HasColumnName("has_nutrition_discrepancy");

                    b.Property<long>("ImportedProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("imported_product_id");

                    b.Property<int>("MatchStatus")
                        .HasColumnType("integer")
                        .HasColumnName("match_status");

                    b.Property<long?>("OpenFoodFactsProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("open_food_facts_product_id");

                    b.HasKey("Id")
                        .HasName("p_k_comparison_results");

                    b.HasIndex("ComparedAt")
                        .HasDatabaseName("ix_comparison_results_compared_at");

                    b.HasIndex("ComparisonBatchId")
                        .HasDatabaseName("ix_comparison_results_comparison_batch_id");

                    b.HasIndex("ImportedProductId")
                        .HasDatabaseName("ix_comparison_results_imported_product_id");

                    b.HasIndex("MatchStatus")
                        .HasDatabaseName("ix_comparison_results_match_status");

                    b.HasIndex("OpenFoodFactsProductId")
                        .HasDatabaseName("ix_comparison_results_openfoodfacts_product_id");

                    b.HasIndex("ImportedProductId", "ComparedAt")
                        .HasDatabaseName("ix_comparison_results_product_date");

                    b.ToTable("comparison_results");
                });

            modelBuilder.Entity("KwikOff.Web.Domain.Entities.ImportedProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Allergens")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("allergens");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("barcode");

                    b.Property<string>("Brand")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("brand");

                    b.Property<string>("Category")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("category");

                    b.Property<string>("CurrentLocation")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("current_location");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("DestinationLocation")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("destination_location");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_date");

                    b.Property<string>("FileName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_name");

                    b.Property<DateTime?>("HarvestDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("harvest_date");

                    b.Property<Guid>("ImportBatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("import_batch_id");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at");

                    b.Property<string>("InternalSku")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("internal_sku");

                    b.Property<string>("NormalizedBarcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("normalized_barcode");

                    b.Property<string>("OriginLocation")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("origin_location");

                    b.Property<string>("OriginalData")
                        .HasColumnType("jsonb")
                        .HasColumnName("original_data");

                    b.Property<DateTime?>("PackDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pack_date");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("price");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("product_name");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("quantity");

                    b.Property<DateTime?>("ReceiveDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("receive_date");

                    b.Property<string>("ReferenceDocumentNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference_document_number");

                    b.Property<string>("ReferenceDocumentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference_document_type");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer")
                        .HasColumnName("row_number");

                    b.Property<decimal?>("SalesPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("sales_price");

                    b.Property<DateTime?>("ShipDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ship_date");

                    b.Property<string>("Supplier")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("supplier");

                    b.Property<string>("TenantId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TraceabilityLotCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("traceability_lot_code");

                    b.Property<string>("UnitOfMeasure")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit_of_measure");

                    b.HasKey("Id")
                        .HasName("p_k_imported_products");

                    b.HasIndex("Barcode")
                        .HasDatabaseName("ix_imported_products_barcode");

                    b.HasIndex("Brand")
                        .HasDatabaseName("ix_imported_products_brand");

                    b.HasIndex("ImportBatchId")
                        .HasDatabaseName("ix_imported_products_import_batch_id");

                    b.HasIndex("ImportedAt")
                        .HasDatabaseName("ix_imported_products_imported_at");

                    b.HasIndex("NormalizedBarcode")
                        .HasDatabaseName("ix_imported_products_normalized_barcode");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_imported_products_tenant_id");

                    b.HasIndex("TraceabilityLotCode")
                        .HasDatabaseName("ix_imported_products_tlc");

                    b.HasIndex("TenantId", "NormalizedBarcode")
                        .HasDatabaseName("ix_imported_products_tenant_barcode");

                    b.ToTable("imported_products");
                });

            modelBuilder.Entity("KwikOff.Web.Domain.Entities.OpenFoodFactsProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Allergens")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("allergens");

                    b.Property<string>("AllergensTags")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("allergens_tags");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("barcode");

                    b.Property<string>("Brands")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("brands");

                    b.Property<decimal?>("Carbohydrates100g")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("carbohydrates100g");

                    b.Property<string>("Categories")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("categories");

                    b.Property<string>("CategoriesTags")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("categories_tags");

                    b.Property<int?>("Completeness")
                        .HasColumnType("integer")
                        .HasColumnName("completeness");

                    b.Property<string>("Countries")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("countries");

                    b.Property<string>("CountriesTags")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("countries_tags");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Creator")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("creator");

                    b.Property<string>("Ecoscore")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ecoscore");

                    b.Property<decimal?>("EnergyKcal100g")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("energy_kcal100g");

                    b.Property<decimal?>("Fat100g")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("fat100g");

                    b.Property<decimal?>("Fiber100g")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("fiber100g");

                    b.Property<string>("GenericName")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("generic_name");

                    b.Property<string>("ImageFrontUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_front_url");

                    b.Property<string>("ImageIngredientsUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_ingredients_url");

                    b.Property<string>("ImageNutritionUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_nutrition_url");

                    b.Property<string>("ImageSmallUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_small_url");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<string>("IngredientsText")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("ingredients_text");

                    b.Property<string>("Labels")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("labels");

                    b.Property<string>("LabelsTags")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("labels_tags");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("last_modified_by");

                    b.Property<string>("ManufacturingPlaces")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("manufacturing_places");

                    b.Property<string>("NormalizedBarcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("normalized_barcode");

                    b.Property<string>("NovaGroup")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("nova_group");

                    b.Property<string>("NutritionGrades")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("nutrition_grades");

                    b.Property<string>("Origins")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("origins");

                    b.Property<string>("OriginsTags")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("origins_tags");

                    b.Property<string>("Packaging")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("packaging");

                    b.Property<string>("PackagingTags")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("packaging_tags");

                    b.Property<string>("ProductName")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("product_name");

                    b.Property<decimal?>("Proteins100g")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("proteins100g");

                    b.Property<string>("Quantity")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("quantity");

                    b.Property<string>("RawJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_json");

                    b.Property<decimal?>("Salt100g")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("salt100g");

                    b.Property<decimal?>("SaturatedFat100g")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("saturated_fat100g");

                    b.Property<decimal?>("ServingQuantity")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("serving_quantity");

                    b.Property<string>("ServingSize")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("serving_size");

                    b.Property<decimal?>("Sodium100g")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("sodium100g");

                    b.Property<string>("Stores")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("stores");

                    b.Property<decimal?>("Sugars100g")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("sugars100g");

                    b.Property<string>("Traces")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("traces");

                    b.Property<string>("TracesTags")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("traces_tags");

                    b.HasKey("Id")
                        .HasName("p_k_open_food_facts_products");

                    b.HasIndex("Barcode")
                        .HasDatabaseName("ix_openfoodfacts_products_barcode");

                    b.HasIndex("Brands")
                        .HasDatabaseName("ix_openfoodfacts_products_brands");

                    b.HasIndex("LastModified")
                        .HasDatabaseName("ix_openfoodfacts_products_last_modified");

                    b.HasIndex("NormalizedBarcode")
                        .IsUnique()
                        .HasDatabaseName("ix_openfoodfacts_products_normalized_barcode");

                    b.HasIndex("NutritionGrades")
                        .HasDatabaseName("ix_openfoodfacts_products_nutrition_grades");

                    b.ToTable("open_food_facts_products");
                });

            modelBuilder.Entity("KwikOff.Web.Domain.Entities.SyncStatus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CurrentBatchCount")
                        .HasColumnType("bigint")
                        .HasColumnName("current_batch_count");

                    b.Property<long?>("DownloadedBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("downloaded_bytes");

                    b.Property<bool>("IsSyncing")
                        .HasColumnType("boolean")
                        .HasColumnName("is_syncing");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("LastErrorAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_error_at");

                    b.Property<DateTime?>("LastSyncCompleted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sync_completed");

                    b.Property<DateTime?>("LastSyncStarted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sync_started");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<int>("ProgressPercentage")
                        .HasColumnType("integer")
                        .HasColumnName("progress_percentage");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_name");

                    b.Property<string>("StatusMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("status_message");

                    b.Property<long?>("TotalBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("total_bytes");

                    b.Property<long>("TotalProductsSynced")
                        .HasColumnType("bigint")
                        .HasColumnName("total_products_synced");

                    b.HasKey("Id")
                        .HasName("p_k_sync_statuses");

                    b.HasIndex("IsSyncing")
                        .HasDatabaseName("ix_sync_statuses_is_syncing");

                    b.HasIndex("SourceName")
                        .IsUnique()
                        .HasDatabaseName("ix_sync_statuses_source_name");

                    b.ToTable("sync_statuses");
                });

            modelBuilder.Entity("KwikOff.Web.Domain.Entities.TenantColumnMapping", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ColumnMappingJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("column_mapping_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByUser")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by_user");

                    b.Property<string>("FilePattern")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_pattern");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tenant_id");

                    b.Property<int>("UseCount")
                        .HasColumnType("integer")
                        .HasColumnName("use_count");

                    b.HasKey("Id")
                        .HasName("p_k_tenant_column_mappings");

                    b.HasIndex("LastUsedAt")
                        .HasDatabaseName("ix_tenant_column_mappings_last_used");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_tenant_column_mappings_tenant_id");

                    b.HasIndex("TenantId", "FilePattern")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_column_mappings_tenant_pattern");

                    b.HasIndex("TenantId", "IsActive")
                        .HasDatabaseName("ix_tenant_column_mappings_tenant_active");

                    b.ToTable("tenant_column_mappings");
                });

            modelBuilder.Entity("KwikOff.Web.Domain.Entities.ComparisonResult", b =>
                {
                    b.HasOne("KwikOff.Web.Domain.Entities.ImportedProduct", "ImportedProduct")
                        .WithMany("ComparisonResults")
                        .HasForeignKey("ImportedProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_comparison_results__imported_products_imported_product_id");

                    b.HasOne("KwikOff.Web.Domain.Entities.OpenFoodFactsProduct", "OpenFoodFactsProduct")
                        .WithMany("ComparisonResults")
                        .HasForeignKey("OpenFoodFactsProductId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("f_k_comparison_results__open_food_facts_products_open_food_facts_pr~");

                    b.Navigation("ImportedProduct");

                    b.Navigation("OpenFoodFactsProduct");
                });

            modelBuilder.Entity("KwikOff.Web.Domain.Entities.ImportedProduct", b =>
                {
                    b.Navigation("ComparisonResults");
                });

            modelBuilder.Entity("KwikOff.Web.Domain.Entities.OpenFoodFactsProduct", b =>
                {
                    b.Navigation("ComparisonResults");
                });
#pragma warning restore 612, 618
        }
    }
}
